Controllers/AuthorizationController.cs
using System.IO;
using System.Threading.Tasks;
using Coursework.Domain;
using Coursework.Domain.Entities;
using Coursework.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Coursework.Controllers
{
    public class AuthorizationController: Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ApplicationDbContext _context;

        public AuthorizationController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, 
            IWebHostEnvironment webHostEnvironment, ApplicationDbContext context)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _webHostEnvironment = webHostEnvironment;
            _context = context;
        }

        public IActionResult Login(string returnUrl = null)
        {
            return View(new LoginViewModel()
            {
                ReturnUrl = returnUrl
            });
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser()
                {
                    UserName = model.Username
                };

                var result = await _signInManager.PasswordSignInAsync(model.Username, model.Password, 
                        model.RememberMe, false);

                if (result.Succeeded)
                {
                    if (string.IsNullOrEmpty(model.ReturnUrl) && Url.IsLocalUrl(model.ReturnUrl))
                    {
                        return Redirect(model.ReturnUrl);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Неправильный логин и (или) пароль");
                }
            }

            return View(model);
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model, IFormFile avatarFile)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser user = new ApplicationUser()
                {
                    UserName = model.Username
                };

                var result = await _userManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    string path;
                    if (avatarFile != null)
                    {
                        path = "/Files/" + user.Id + avatarFile.FileName;
                        await using (var fs = new FileStream(_webHostEnvironment.WebRootPath + path, FileMode.Create))
                        {
                            await avatarFile.CopyToAsync(fs);
                        }
                    }
                    else
                        path = "/Files/no_avatar.jpg";

                    user.AvatarUrl = path;
                    await _userManager.UpdateAsync(user);

                    await _signInManager.SignInAsync(user, false);
                    return RedirectToAction("Index", "Home");
                }

                foreach (var error in result.Errors)
                    ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(model);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> SignOut()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult AccessDenied()
        {
            return View();
        }

        [HttpPost]
        public IActionResult LoginExternal(string provider, string returnUrl)
        {
            var redirectUrl = "Authorization/LoginExternalCallback";
            var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
            return Challenge(properties, provider);
        }

        public async Task<IActionResult> LoginExternalCallback()
        {
            var info = await _signInManager.GetExternalLoginInfoAsync();
            if (info == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var result = await _signInManager.ExternalLoginSignInAsync(info.LoginProvider,
                info.ProviderKey, true, false);
            if (result.Succeeded)
            {
                return RedirectToAction("Index", "Home");
            }

            return RedirectToAction(nameof(RegisterExternal));
        }

        public IActionResult RegisterExternal()
        {
            return View();
        }

        [HttpPost]
        [ActionName(nameof(RegisterExternal))]
        public async Task<IActionResult> RegisterExternalConfirmed(RegisterExternalViewModel model)
        {
            var info = await _signInManager.GetExternalLoginInfoAsync();
            if (info == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var user = new ApplicationUser { UserName = model.Username, AvatarUrl = "/Files/no_avatar.jpg"};

            var result = await _userManager.CreateAsync(user);
            if (result.Succeeded)
            {
                var identityResult = await _userManager.AddLoginAsync(user, info);
                if (identityResult.Succeeded)
                {
                    await _signInManager.SignInAsync(user, true);
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("Username", "This account is already registered.");
            }
            else
                ModelState.AddModelError("Username", "This name is already in use.");


            return View(model);
        }
    }
}

Views/Shared/CssPartial.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration _configuration

@{
    string bootstrapPath = "/lib/bootstrap/css/bootstrap.css";
    if (Context.Request.Cookies.ContainsKey("themeCookie"))
    {
        var cookieValue = Context.Request.Cookies["themeCookie"];
        bootstrapPath = _configuration.GetSection("ThemeFiles")[cookieValue] ?? bootstrapPath;
    }
}
<link rel="stylesheet" href="@bootstrapPath" />
<link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap-social.css"/>
<link rel="stylesheet" href="~/lib/datatables/media/css/jquery.dataTables.min.css" />
<link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css">
<link rel="stylesheet" href="~/lib/simplemde/dist/simplemde.min.css">
<link rel="stylesheet" href="~/lib/bootstrap-star-rating/themes/krajee-svg/theme.min.css"/>
<link rel="stylesheet" href="~/lib/bootstrap-star-rating/css/star-rating.min.css"/>
<link rel="stylesheet" href="~/css/site.css" />

Views/Shared/FooterPartial.cshtml
<footer class="border-top pb-1 pt-1 footer text-muted">
    <div class="container">
        &copy; 2021 - Coursework
    </div>
</footer>

Views/Shared/HeaderPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Coursework.Domain.Entities
@using Microsoft.AspNetCore.Hosting
@inject UserManager<ApplicationUser> _userManager
@inject IWebHostEnvironment _webHostEnvironment
@inject IHtmlLocalizer<SharedResource> _sharedLocalizer

    <header class="py-3 bg-light text-white">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                @*<a class="align-items-center text-black text-decoration-none
                      col-12 col-lg-auto me-lg-auto"
                   asp-controller="Home" asp-action="Index">Coursework</a>*@
                
                <a class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none"
                   asp-controller="Home" asp-action="Index">
                    Coursework
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0 ms-2">
                    <li><a asp-controller="Account" asp-action="Settings" 
                           class="nav-link px-2 link-secondary">@_sharedLocalizer["Settings"]</a></li>
                </ul>

                <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3 flex-last"
                      asp-controller="Home" asp-action="Search">
                    <input type="search" class="form-control form-control-dark" placeholder="@_sharedLocalizer["SearchPlaceholder"]"
                           aria-label="Search" name="searchString">
                </form>
                <div class="text-end">
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <a asp-controller="Authorization" asp-action="Login" class="btn btn-outline-dark me-2">@_sharedLocalizer["Login"]</a>
                        <a asp-controller="Authorization" asp-action="Register" class="btn btn-warning">@_sharedLocalizer["Register"]</a>
                    }
                    else
                    {
                        var user = await _userManager.FindByIdAsync(_userManager.GetUserId(User));

                        <div class="flex-shrink-0 dropdown">
                            <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
                                <img src="@user.AvatarUrl" alt="mdo" width="32" height="32" class="rounded-circle">
                            </a>
                            <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2" style="">
                                <li><a class="dropdown-item" asp-controller="Account" asp-action="Profile">@_sharedLocalizer["PersonalAccount"]</a></li>
                                <li><a class="dropdown-item" asp-controller="Account" asp-action="Settings">@_sharedLocalizer["Settings"]</a></li>
                                @if (User.IsInRole("Admin"))
                                {
                                    <li><a class="dropdown-item" asp-controller="Account" asp-action="Admin">@_sharedLocalizer["AdminPanel"]</a></li>
                                }
                                <li><hr class="dropdown-divider"></li>
                                <li>
                                    <form method="post" asp-controller="Authorization" asp-action="SignOut">
                                        <input class="dropdown-item" type="submit" value="@_sharedLocalizer["SignOut"]" />
                                    </form>
                                </li>
                            </ul>
                        </div>
                    }
                </div>
            </div>
        </div>
    </header>

Views/Shared/MetatagsPartial.cshtml
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

Views/Shared/ScriptsPartial.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/lib/bootstrap-star-rating/js/star-rating.min.js"></script>
<script src="~/lib/bootstrap-star-rating/themes/krajee-svg/theme.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"] - Coursework</title>
    @await Html.PartialAsync("MetatagsPartial")
    @await Html.PartialAsync("CssPartial")
    @RenderSection("Styles", required: false)
</head>
<body>
    @await Html.PartialAsync("HeaderPartial")
    <div class="container">
        <main role="main" class="col-12 pb-3 pt-2">
            @RenderBody()
        </main>
    </div>
    @await Html.PartialAsync("FooterPartial")
    
    @await Html.PartialAsync("ScriptsPartial")
    @RenderSection("Scripts", required: false)
</body>
</html>